name: fl_graphics
description: Graphics in flutter using custom paint
version: 1.0.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4


dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
